name: Deploy

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/build-and-test

      - uses: ./.github/actions/create-release-artifacts

      - name: Create GitHub release
        uses: ncipollo/release-action@v1.21.0
        with:
          artifacts: "publish/*.exe,publish/*.msi"
          allowUpdates: true
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
